name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore "${{ github.workspace }}/ExampleLib.slnx"

      - name: Build
        run: dotnet build "${{ github.workspace }}/ExampleLib.slnx" --configuration Release --no-restore

      - name: Pack
        run: dotnet pack "${{ github.workspace }}/ExampleLib.slnx" --configuration Release --no-build --output "${{ github.workspace }}/artifacts/packages"

      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: ExampleLib-packages
          path: ${{ github.workspace }}/artifacts/packages/*.nupkg
